apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topics
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: bitnami/kafka:latest
        command:
        - /bin/bash
        - -c
        - |
          kafka-topics.sh --create --bootstrap-server kafka-service:9092 --replication-factor 1 --partitions 1 --topic auth-otp-topic
          kafka-topics.sh --create --bootstrap-server kafka-service:9092 --replication-factor 1 --partitions 1 --topic new-user-topic
          kafka-topics.sh --create --bootstrap-server kafka-service:9092 --replication-factor 1 --partitions 1 --topic create-chat-topic
          kafka-topics.sh --create --bootstrap-server kafka-service:9092 --replication-factor 1 --partitions 1 --topic notification-topic
      restartPolicy: Never
  backoffLimit: 4