apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentor-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mentor-chat-service
  template:
    metadata:
      labels:
        app: mentor-chat-service
    spec:
      containers:
        - name: mentor-chat-service
          image: sriraghariharan/mentor-chat-service-image:latest
          ports:
            - containerPort: 6006
          envFrom:
            - configMapRef:
                name: chat-config
---
apiVersion: v1
kind: Service
metadata:
  name: mentor-chat-service
spec:
  selector:
    app: mentor-chat-service
  ports:
    - protocol: TCP
      port: 6006
      targetPort: 6006