apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentor-email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mentor-email-service
  template:
    metadata:
      labels:
        app: mentor-email-service
    spec:
      containers:
        - name: mentor-email-service
          image: sriraghariharan/mentor-email-service-image:latest
          ports:
            - containerPort: 6008
          envFrom:
            - configMapRef:
                name: email-config 
---
apiVersion: v1
kind: Service
metadata:
  name: mentor-email-service
spec:
  selector:
    app: mentor-email-service
  ports:
  - protocol: TCP
    port: 6008
    targetPort: 6008