apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentor-notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mentor-notification-service
  template:
    metadata:
      labels:
        app: mentor-notification-service
    spec:
      containers:
      - name: mentor-notification-service
        image: sriraghariharan/mentor-notification-service-image
        ports:
        - containerPort: 6009
        envFrom:
        - configMapRef:
            name: notification-config
---
apiVersion: v1
kind: Service
metadata:
  name: mentor-notification-service
spec:
  selector:
    app: mentor-notification-service
  ports:
  - protocol: TCP
    port: 6009
    targetPort: 6009
