apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentor-profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mentor-profile-service
  template:
    metadata:
      labels:
        app: mentor-profile-service
    spec:
      containers:
      - name: mentor-profile-service
        image: sriraghariharan/mentor-profile-service-image
        ports:
        - containerPort: 6002
        envFrom:
        - configMapRef:
            name: profile-config
---
apiVersion: v1
kind: Service
metadata:
  name: mentor-profile-service
spec:
  selector:
    app: mentor-profile-service
  ports:
  - protocol: TCP
    port: 6002
    targetPort: 6002
