apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentor-frontend-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mentor-frontend-admin-service
  template:
    metadata:
      labels:
        app: mentor-frontend-admin-service
    spec:
      containers:
      - name: mentor-frontend-admin-service
        image: sriraghariharan/mentor-frontend-admin-image
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: mentor-frontend-admin-service
spec:
  selector:
    app: mentor-frontend-admin-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001