name: dockerhub-frontend-service

on:
  push:
    branches: [ "main" ]
    paths: ["frontend/**"]
    
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  run: cd frontend && docker build -t ${{ secrets.DOCKER_USERNAME }}/mentor-frontend-image .
      -  run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      -  run: docker push ${{secrets.DOCKER_USERNAME}}/mentor-frontend-image

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [dockerize]

  #   steps:
  #     - name: Set up Google Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v1
  #       with:
  #         service_account_key: ${{ secrets.GKE_SA_KEY }}
  #         project_id: ${{ secrets.GKE_PROJECT_ID }}
      
  #     - name: Authenticate to GKE
  #       run: |
  #         ${{ secrets.GKE_CONNECTION_STRING }}

  #     - name: Delete Existing Deployment
  #       run: |
  #         kubectl delete -f deployment mentor-frontend-deployment || true

  #     - name: Apply New Deployment
  #       run: |
  #         kubectl apply -f k8s/frontend/frontend-depl.yaml