name: frontend-admin-service

on:
  push:
    branches: [ "main" ]
    paths: ["frontend-admin/**"]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  run: cd frontend-admin && docker build -t ${{ secrets.DOCKER_USERNAME }}/mentor-frontend-admin-image .
      -  run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      -  run: docker push ${{secrets.DOCKER_USERNAME}}/mentor-frontend-admin-image