name: notification-service

on:
  push:
    branches: [ "main" ]
    paths: ["notification service/**"]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  run: cd 'notification service' && docker build -t ${{ secrets.DOCKER_USERNAME }}/mentor-notification-service-image .
      -  run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      -  run: docker push ${{secrets.DOCKER_USERNAME}}/mentor-notification-service-image