name: webinar-service

on:
  push:
    branches: [ "main" ]
    paths: ["webinar service/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # checkout the repository

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

  dockerize:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # checkout the repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mentor-webinar-service .
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mentor-webinar-service


# mongodb passwords
# sriraghariharan108    1LbGtp9Lyj51uK6e

# connection code
# mongodb+srv://sriraghariharan108:1LbGtp9Lyj51uK6e@mentor-cluster.lvg1u.mongodb.net/?retryWrites=true&w=majority&appName=MEntor-cluster
# mongodb+srv://sriraghariharan108:<db_password>@mentor-cluster.lvg1u.mongodb.net/?retryWrites=true&w=majority&appName=MEntor-cluster